-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aluno
(
    idaluno integer NOT NULL DEFAULT nextval('aluno_idaluno_seq'::regclass),
    nome character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cpf character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rg character varying(90) COLLATE pg_catalog."default",
    datanascimento date,
    sexo character varying(45) COLLATE pg_catalog."default",
    raca character varying(45) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default",
    endereco character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(60) COLLATE pg_catalog."default",
    cep character varying(90) COLLATE pg_catalog."default",
    uf character varying(45) COLLATE pg_catalog."default",
    telefone character varying(60) COLLATE pg_catalog."default",
    nome_escola character varying(120) COLLATE pg_catalog."default" NOT NULL,
    endereco_escola character varying(120) COLLATE pg_catalog."default",
    cidade_escola character varying(45) COLLATE pg_catalog."default",
    cep_escola character varying(45) COLLATE pg_catalog."default",
    uf_escola character varying(45) COLLATE pg_catalog."default",
    turno character varying(90) COLLATE pg_catalog."default",
    grau character varying(90) COLLATE pg_catalog."default",
    datainclusao date,
    desligamento date,
    peso character varying(45) COLLATE pg_catalog."default",
    altura character varying(45) COLLATE pg_catalog."default",
    camisa character varying(45) COLLATE pg_catalog."default",
    short character varying(45) COLLATE pg_catalog."default",
    calcado character varying(45) COLLATE pg_catalog."default",
    grupo_sanguineo character varying(60) COLLATE pg_catalog."default",
    medicacao character varying(60) COLLATE pg_catalog."default",
    mae character varying(120) COLLATE pg_catalog."default",
    pai character varying(120) COLLATE pg_catalog."default",
    responsavel character varying(120) COLLATE pg_catalog."default",
    telefone_mae character varying(60) COLLATE pg_catalog."default",
    telefone_pai character varying(60) COLLATE pg_catalog."default",
    telefone_responsavel character varying(60) COLLATE pg_catalog."default",
    parentesco_responsavel character varying(60) COLLATE pg_catalog."default",
    profissao_mae character varying(100) COLLATE pg_catalog."default",
    profissao_pai character varying(100) COLLATE pg_catalog."default",
    profissao_responsavel character varying(100) COLLATE pg_catalog."default",
    termo character varying(2000) COLLATE pg_catalog."default",
    nucleo_atendimento_idnucleo_atendimento integer NOT NULL,
    nucleo_treinamento_idnucleo_treinamento integer NOT NULL,
    treino_semanal_idtreino_semanal integer NOT NULL,
    categoria_idcategoria integer NOT NULL,
    horario_idhorario integer NOT NULL,
    modalidade_idmodalidade integer NOT NULL,
    CONSTRAINT aluno_pkey PRIMARY KEY (idaluno)
);

CREATE TABLE IF NOT EXISTS public.categoria
(
    idcategoria integer NOT NULL DEFAULT nextval('categoria_idcategoria_seq'::regclass),
    idade character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT categoria_pkey PRIMARY KEY (idcategoria)
);

CREATE TABLE IF NOT EXISTS public.colaborador
(
    idcolaborador integer NOT NULL DEFAULT nextval('colaborador_idcolaborador_seq'::regclass),
    nome character varying(120) COLLATE pg_catalog."default",
    cpf character varying(100) COLLATE pg_catalog."default",
    rg character varying(90) COLLATE pg_catalog."default",
    datanascimento date,
    sexo character varying(45) COLLATE pg_catalog."default",
    raca character varying(45) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default" NOT NULL,
    endereco character varying(120) COLLATE pg_catalog."default",
    cidade character varying(90) COLLATE pg_catalog."default",
    cep character varying(90) COLLATE pg_catalog."default",
    uf character varying(45) COLLATE pg_catalog."default",
    telefone character varying(90) COLLATE pg_catalog."default",
    profissao character varying(100) COLLATE pg_catalog."default",
    perfil_idperfil integer NOT NULL,
    nucleo_atendimento_idnucleo_atendimento integer NOT NULL,
    CONSTRAINT colaborador_pkey PRIMARY KEY (idcolaborador)
);

CREATE TABLE IF NOT EXISTS public.empresas
(
    idempresas integer NOT NULL DEFAULT nextval('empresas_idempresas_seq'::regclass),
    cnpj character varying(100) COLLATE pg_catalog."default" NOT NULL,
    razao_social character varying(255) COLLATE pg_catalog."default",
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    endereco character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(60) COLLATE pg_catalog."default",
    cep character varying(90) COLLATE pg_catalog."default",
    uf character varying(45) COLLATE pg_catalog."default",
    segmento character varying(90) COLLATE pg_catalog."default",
    tipo_empresa character varying(120) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default",
    telefone_local character varying(90) COLLATE pg_catalog."default",
    nome_empresario character varying(120) COLLATE pg_catalog."default" NOT NULL,
    telefone_pessoal character varying(90) COLLATE pg_catalog."default",
    nucleo_atendimento_idnucleo_atendimento integer NOT NULL,
    CONSTRAINT empresas_pkey PRIMARY KEY (idempresas)
);

CREATE TABLE IF NOT EXISTS public.familia
(
    idfamilia integer NOT NULL DEFAULT nextval('familia_idfamilia_seq'::regclass),
    nome_chefe_familia character varying(120) COLLATE pg_catalog."default" NOT NULL,
    sexo character varying(45) COLLATE pg_catalog."default",
    cpf character varying(90) COLLATE pg_catalog."default" NOT NULL,
    endereco character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(90) COLLATE pg_catalog."default",
    cep character varying(90) COLLATE pg_catalog."default",
    uf character varying(45) COLLATE pg_catalog."default",
    email character varying(120) COLLATE pg_catalog."default",
    telefone character varying(90) COLLATE pg_catalog."default",
    nucleo_familiar character varying(90) COLLATE pg_catalog."default",
    moradia character varying(60) COLLATE pg_catalog."default",
    nucleo_atendimento_idnucleo_atendimento integer NOT NULL,
    CONSTRAINT familia_pkey PRIMARY KEY (idfamilia)
);

CREATE TABLE IF NOT EXISTS public.horario
(
    idhorario integer NOT NULL DEFAULT nextval('horario_idhorario_seq'::regclass),
    hora time without time zone,
    CONSTRAINT horario_pkey PRIMARY KEY (idhorario)
);

CREATE TABLE IF NOT EXISTS public.login
(
    idlogin integer NOT NULL DEFAULT nextval('login_idlogin_seq'::regclass),
    nome character varying(120) COLLATE pg_catalog."default" NOT NULL,
    login character varying(45) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    senha character varying(120) COLLATE pg_catalog."default",
    perfil_idperfil integer NOT NULL,
    CONSTRAINT login_pkey PRIMARY KEY (idlogin)
);

CREATE TABLE IF NOT EXISTS public.modalidade
(
    idmodalidade integer NOT NULL DEFAULT nextval('modalidade_idmodalidade_seq'::regclass),
    descricao character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT modalidade_pkey PRIMARY KEY (idmodalidade)
);

CREATE TABLE IF NOT EXISTS public.nucleo_atendimento
(
    idnucleo_atendimento integer NOT NULL DEFAULT nextval('nucleo_atendimento_idnucleo_atendimento_seq'::regclass),
    sede character varying(120) COLLATE pg_catalog."default" NOT NULL,
    telefone_sede character varying(90) COLLATE pg_catalog."default",
    email_email character varying(120) COLLATE pg_catalog."default",
    endereco_sede character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cidade_sede character varying(90) COLLATE pg_catalog."default",
    cep_sede character varying(90) COLLATE pg_catalog."default",
    uf_sede character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT nucleo_atendimento_pkey PRIMARY KEY (idnucleo_atendimento)
);

CREATE TABLE IF NOT EXISTS public.nucleo_treinamento
(
    idnucleo_treinamento integer NOT NULL DEFAULT nextval('nucleo_treinamento_idnucleo_treinamento_seq'::regclass),
    nome_responsavel character varying(120) COLLATE pg_catalog."default" NOT NULL,
    telefone_responsavel character varying(60) COLLATE pg_catalog."default",
    local character varying(120) COLLATE pg_catalog."default" NOT NULL,
    cidade character varying(60) COLLATE pg_catalog."default",
    cep character varying(90) COLLATE pg_catalog."default",
    telefone_local character varying(60) COLLATE pg_catalog."default",
    uf character varying(45) COLLATE pg_catalog."default",
    nucleo_atendimento_idnucleo_atendimento integer NOT NULL,
    CONSTRAINT nucleo_treinamento_pkey PRIMARY KEY (idnucleo_treinamento)
);

CREATE TABLE IF NOT EXISTS public.perfil
(
    idperfil integer NOT NULL DEFAULT nextval('perfil_idperfil_seq'::regclass),
    perfil character varying(90) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perfil_pkey PRIMARY KEY (idperfil)
);

CREATE TABLE IF NOT EXISTS public.treino_semanal
(
    idtreino_semanal integer NOT NULL DEFAULT nextval('treino_semanal_idtreino_semanal_seq'::regclass),
    semana character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT treino_semanal_pkey PRIMARY KEY (idtreino_semanal)
);

ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_categoria1 FOREIGN KEY (categoria_idcategoria)
    REFERENCES public.categoria (idcategoria) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_categoria1_idx
    ON public.aluno(categoria_idcategoria);


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_horario1 FOREIGN KEY (horario_idhorario)
    REFERENCES public.horario (idhorario) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_horario1_idx
    ON public.aluno(horario_idhorario);


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_modalidade1 FOREIGN KEY (modalidade_idmodalidade)
    REFERENCES public.modalidade (idmodalidade) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_modalidade1_idx
    ON public.aluno(modalidade_idmodalidade);


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_nucleo_atendimento1 FOREIGN KEY (nucleo_atendimento_idnucleo_atendimento)
    REFERENCES public.nucleo_atendimento (idnucleo_atendimento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_nucleo_atendimento1_idx
    ON public.aluno(nucleo_atendimento_idnucleo_atendimento);


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_nucleo_treinamento1 FOREIGN KEY (nucleo_treinamento_idnucleo_treinamento)
    REFERENCES public.nucleo_treinamento (idnucleo_treinamento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_nucleo_treinamento1_idx
    ON public.aluno(nucleo_treinamento_idnucleo_treinamento);


ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_aluno_treino_semanal1 FOREIGN KEY (treino_semanal_idtreino_semanal)
    REFERENCES public.treino_semanal (idtreino_semanal) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_aluno_treino_semanal1_idx
    ON public.aluno(treino_semanal_idtreino_semanal);


ALTER TABLE IF EXISTS public.colaborador
    ADD CONSTRAINT fk_colaborador_nucleo_atendimento1 FOREIGN KEY (nucleo_atendimento_idnucleo_atendimento)
    REFERENCES public.nucleo_atendimento (idnucleo_atendimento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_colaborador_nucleo_atendimento1_idx
    ON public.colaborador(nucleo_atendimento_idnucleo_atendimento);


ALTER TABLE IF EXISTS public.colaborador
    ADD CONSTRAINT fk_colaborador_perfil1 FOREIGN KEY (perfil_idperfil)
    REFERENCES public.perfil (idperfil) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_colaborador_perfil1_idx
    ON public.colaborador(perfil_idperfil);


ALTER TABLE IF EXISTS public.empresas
    ADD CONSTRAINT fk_empresas_nucleo_atendimento1 FOREIGN KEY (nucleo_atendimento_idnucleo_atendimento)
    REFERENCES public.nucleo_atendimento (idnucleo_atendimento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_empresas_nucleo_atendimento1_idx
    ON public.empresas(nucleo_atendimento_idnucleo_atendimento);


ALTER TABLE IF EXISTS public.familia
    ADD CONSTRAINT fk_familia_nucleo_atendimento1 FOREIGN KEY (nucleo_atendimento_idnucleo_atendimento)
    REFERENCES public.nucleo_atendimento (idnucleo_atendimento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_familia_nucleo_atendimento1_idx
    ON public.familia(nucleo_atendimento_idnucleo_atendimento);


ALTER TABLE IF EXISTS public.login
    ADD CONSTRAINT fk_login_perfil1 FOREIGN KEY (perfil_idperfil)
    REFERENCES public.perfil (idperfil) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_login_perfil1_idx
    ON public.login(perfil_idperfil);


ALTER TABLE IF EXISTS public.nucleo_treinamento
    ADD CONSTRAINT fk_nucleo_treinamento_nucleo_atendimento1 FOREIGN KEY (nucleo_atendimento_idnucleo_atendimento)
    REFERENCES public.nucleo_atendimento (idnucleo_atendimento) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS fk_nucleo_treinamento_nucleo_atendimento1_idx
    ON public.nucleo_treinamento(nucleo_atendimento_idnucleo_atendimento);

END;